### ISSUE TITLE
missing .inc file

### ISSUE THREAD

**Issue by jarikomppa** [MobyGamer/MONOTONE#1]
Source files refer to an .inc file that does not appear in the depot.

**Comment by MobyGamer** [comment]
Which .INC file?

**Comment by jarikomppa** [comment]
{To alter compile-time defaults, please edit MT_DEFS.INC.  This file contains
compile-time defines like whether profiling is on, types of debugging, etc.}

{$I MT_DEFS.INC}

**Comment by MobyGamer** [comment]
My mistake, sorry!  It's on the repo now.
