### ISSUE TITLE
It doesn't work for Windows

### ISSUE THREAD

**Issue by 1IoMoth** [MobyGamer/MONOTONE#10]
I don't know if this was intentional or not but I cannot open the .exe file without the message that it doesn't work on my PC

**Comment by ITzTravelInTime** [comment]
That .exe file can be only executed on ms-dos and 32 bit windows versions, because it's a 16 bit .exe file for ms-dos computers, this program has been made for that os afterall

**Comment by Sasytoremember** [comment]
you can run it with this: 
[WineVDM.zip](https://github.com/MobyGamer/MONOTONE/files/5890984/WineVDM.zip)

**Comment by Sasytoremember** [comment]
if you're on modern

**Comment by EliMCGamerGuy** [comment]
You can use DOSBox!

**Comment by MobyGamer** [comment]
Monotone is a DOS program and must be used in either real DOS, or in emulators.
