### ISSUE TITLE
Giving undef answer to questions crashes

### ISSUE THREAD

**Issue by jarikomppa** [MobyGamer/MONOTONE#3]
Pressing a wrong key in the startup questions (like enter or too big/small number) gives Runtime error 201.

**Comment by MobyGamer** [comment]
On 4/12/2015 11:22 AM, Jari Komppa wrote:

> Pressing a wrong key in the startup questions (like enter or too
> big/small number) gives Runtime error 201.

Yes, the entire startup part is decidedly un-robust :-)  Optimized for  size, not grace.
