### ISSUE TITLE
[Feature] Linux support?

### ISSUE THREAD

**Issue by mikedebian** [MobyGamer/MONOTONE#6]
I don't know if it's of any interest, but a linux build would be very nice.

**Comment by MobyGamer** [comment]
It would be nice, but the entire thing is written in dead languages and would be one hell of a porting job to freepascal + ncurses.  And I don't even know if there's a consistent interface or API for the speaker in Linux, so I guess it would have to use another API like PortAudio or PulseAudio.  Way beyond my interest level, but I certainly won't stop people from forking.

**Comment by jarikomppa** [comment]
Tried, for the fun of it, to run monotone through some pascal-to-c
converter. Didn't work. =)

**Comment by MobyGamer** [comment]
Yes, but then again, most pascal-to-c converters don't work (which surprises me, but is true).

**Comment by FreeFull** [comment]
Writing your own clone of MONOTONE could be a fun project to try ;)
